### ISSUE TITLE
Google lighthouse scoring require default width and height

### ISSUE THREAD

**Issue by LucGosso** [ErikHen/PictureRenderer.Optimizely#11]
Hello!! good work so far =) 

We need the possibility to add explicit width and height

"Image elements do not have explicit width and height"
Set an explicit width and height on image elements to reduce layout shifts and improve CLS. [Learn more](https://web.dev/optimize-cls/?utm_source=lighthouse&utm_medium=lr#images-without-dimensions)

![image](https://user-images.githubusercontent.com/9716195/198028604-0273539c-9868-4adc-be64-385037caa03e.png)

im looking for function like @Html.EditorFor(m => m.Foo, new { htmlAttributes = new { @class = "foo", width="500" } })

Could we add or change PictureHelper => 
@Html.Picture(m => m.MyImage, profile, new { htmlAttributes = new { @class = "foo", width="500", height="800" loading="lazy" } })

**Comment by ErikHen** [comment]
Hi. Thanks! It is possible, just not very well documented.
In your picture profile: 
Set ImgWidthHeight  - If true, width and height attributes will be rendered on the img element.

Will update the docs.

**Comment by LucGosso** [comment]
great Erik! 

one step closer

![image](https://user-images.githubusercontent.com/9716195/198078345-2cb8dc90-78a1-41da-8c03-af71abae9ddf.png)
