### ISSUE TITLE
Picture displayed as a square though should be a rectangle

### ISSUE THREAD

**Issue by vilijatr** [ErikHen/PictureRenderer.Optimizely#16]
We are using Optimizely, CMS version 12 and have switched to to picture renderer from image processor . 
Now there is an image in the mega menu which is displayed as a square though it should be just a rectangle, it should not be cropped nor reshaped. 
![image](https://github.com/ErikHen/PictureRenderer.Optimizely/assets/20964843/a41d1997-be5b-4d29-9a43-43ae628f1521)
The css looks the same in the old and new solutions
![image](https://github.com/ErikHen/PictureRenderer.Optimizely/assets/20964843/031da022-828b-4719-9761-cc7cf8b64974)
In the html now we see that height is being added which previously was not. 
![image](https://github.com/ErikHen/PictureRenderer.Optimizely/assets/20964843/495f3231-8412-41b8-b4a3-ad7e3139bffc)
Any suggestions why it is this way?

**Comment by ErikHen** [comment]
Hi, I'm guessing that the aspect ratio in your picture profile is set to 1. The value 1 means that width and height should be equal. Your wanted image width divided by your wanted image height is your wanted aspect ratio (ex. 640/480 = 1.34).
See more samples here: https://github.com/ErikHen/PictureRenderer.Optimizely#1-define-picture-profiles

**Comment by vilijatr** [comment]
Ok, thanks. I thought if no profile was being specified it would show the image as it is. 
Created a new profile, added it to the partial view also the css class (it was not taking one from the cshtml) and now it looks correct.
