### ISSUE TITLE
PictureHelper GetUrl with context mode default

### ISSUE THREAD

**Issue by FreddyA** [ErikHen/PictureRenderer.Optimizely#17]
Is it possible to have the option to get the urls (UrlResolver.GetUrl) in picturehelper with ContextMode.Default. Right now the urls will be in edit mode when using preview in optimizely (ends with ,,id?editmode=true...), which makes them not use imagesharp...

**Comment by ErikHen** [comment]
Thanks for that suggestion. Not sure if I want it to be a setting or not.
You are welcome to make a pull requests, as I currently don't really have the time to do it myself.
