### ISSUE TITLE
RenderXhtmlString does not support set styles for images

### ISSUE THREAD

**Issue by nguyejon-te** [ErikHen/PictureRenderer.Optimizely#19]
The Tinymce enables images to be set with different alignments and this is essentially adding a `style="float: right;"` attribute for the image. After processing of the image using the RenderXhtmlString the style attribute is omitted.

We can of course remedy this issue by instructing the users to add a class to handle the alignment, but is there something that could be done without this work around?

**Comment by ErikHen** [comment]
Thanks for letting me know. I will look into this.

**Comment by ErikHen** [comment]
Please test with v3.1. The style attribute should be carried forward to the img element in the picture element.
