### ISSUE TITLE
[Request] Need to provide a nonce attribute

### ISSUE THREAD

**Issue by jocpih-dec** [ErikHen/PictureRenderer.Optimizely#22]
Hi!
I have a client who takes security very seriously. I would need to add a nonce attribute to the script tag when it is rendered. Would it be possible to get an extra parameter, "nonceValue" or something similar, to Picture Html helper?

_Picture Html helper:_
@Html.Picture(Model.CurrentPage.TestImage1, PictureProfiles.SampleImage, nonceValue: "theProvidedValueInNonceValueParameter")

_Rendered code:_
<div id="pinfof57af36456"...></div>
<script type="text/javascript" nonce="theProvidedValueInNonceValueParameter"> window.addEventListener("load",function () { const pictureInfo.....</script>

**Comment by ErikHen** [comment]
Hi. I'm not sure I understand. A script tag is only rendered when having ShowInfo=true in the picture profile. Showing that information is only for debug/demo purpose. 
You will not have an issue if not setting that property(?).

**Comment by jocpih-dec** [comment]
Ah. sorry... when I wrote this I was still playing around, the focus point did not work (still doesn't). I played around some more and noticed the script tag wasn't there in the profiles without ShowInfo. 

So need to figure out how I can get the focus point to work then.  But we can close this request. Would still be helpful though, needed to remove all csp settings and allow everything to see the info. But not a big deal since it would never be used in production.

Tack så mycket ändå! Gillar PictureRenderer! 😄   Bara jag får igång Focus Point också!

**Comment by ErikHen** [comment]
👍 what issue do you have with the focal point? 
If it isn't added to the querystring it probably can't find it on the image content.
Have you added a property with this exact name?
`public virtual string ImageFocalPoint { get; set; }`

**Comment by jocpih-dec** [comment]
oh, it's added, I can see it as rxy, I think it was, in the querystring. But it's not working, changing size on the screen doesn't affect the image. So must be missing something else. Seem to remember last time I tried PictureRenderer, in an Optimizely 11 project, it worked just fine. Maybe just should try to download your example project and try that out first. See what I'm missing.

**Comment by ErikHen** [comment]
If you are changing the window size after the image is loaded the browser might not select to show another image. Try with Firefox, it doesn't try to be smart by not downloading a new image if it already have downloaded a higher resolution (at least when I tested some years ago).
Check the rendered source and open the different images in separate tabs.

**Comment by jocpih-dec** [comment]
Thanks, I'll play around a some more! Trevlig helg!
