### ISSUE TITLE
Html-validation errors

### ISSUE THREAD

**Issue by jonatanjii** [ErikHen/PictureRenderer.Optimizely#9]
Hi we get html-validation errors for our images:
There seem to be spaces missing in source and img

Below we use the following profile:

public static readonly PictureProfile PersonBlockImage = new()
        {
            SrcSetWidths = new[] { 200 },
            Sizes = new[] { "100vw" },
            AspectRatio = 1,
            CreateWebpForFormat = null,
            Quality = 90
        };

![image](https://user-images.githubusercontent.com/23709074/195020633-3e43a13f-d233-4720-99e2-e4eeaa79a865.png)

![image](https://user-images.githubusercontent.com/23709074/195020035-1f454580-e927-4540-ac91-61facefcd3ab.png)

/Jonatan

**Comment by ErikHen** [comment]
Hi. Update to latest version of [Picturerenderer ](https://www.nuget.org/packages/PictureRenderer)  . 
I'll keep this issue open until I've updated this nuget.

**Comment by ErikHen** [comment]
v2.4.0 use latest version of PictureRenderer which have more compliant rendering.

**Comment by jonatanjii** [comment]
Thanks!
